# Generated by Django 5.1.8 on 2025-04-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='memo',
            table='app_memo',
        ),
    ]
